core/about_us/urls.py
from django.urls import path
from . import views

app_name='about'

urlpatterns=[
    path('about',views.AboutUs.as_view(),name='about_us'),
    path('contact',views.ContactUs.as_view(),name='contact_us'),
    path('questions',views.QuestionView.as_view(),name='questions')
]

core/core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('account/',include('user_profile.urls')),
    path('about/',include('about_us.urls')),
    path('',include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/includes/footer.html
{%load static%}
<footer id="contact" class="footer-one iq-bg-dark">
     
        <!-- Address -->
        <div class="footer-top">
            <div class="container-fluid">
                <div class="row footer-standard">
                    <div class="col-lg-7">
                        <div class="widget text-left">
                            <div class="menu-footer-link-1-container">
                                <ul id="menu-footer-link-1" class="menu p-0">
                                    <li id="menu-item-7314" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7314">
                                        <a href="{%url 'about:contact_us'%}">ارتباط با ما</a>
                                    </li>
                                    <li id="menu-item-7316" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7316">
                                        <a href="{%url 'about:about_us'%}">درباره ما</a>
                                    </li>
                                    <li id="menu-item-7118" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7118">
                                       <a href="{%url 'about:questions'%}">سوالات متداول</a>
                                   </li>
                                    <!-- <li id="menu-item-7118" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7118">
                                        <a href="../html/watch-video.html">لیست تماشا</a>
                                    </li> -->
                                </ul>
                            </div>
                        </div>
                        <div class="widget text-left">			
                            <div class="textwidget">
                                <p><small> ساخته شده توسط<a class="text-primary title" href="www.mhsrbi.ir/">محسن سرابی </a></small></p>
                            </div>
                        </div>                        
                    </div>
                    <div class="col-lg-2 col-md-6 mt-4 mt-lg-0">
                        <h6 class="footer-link-title">
                            ما را دنبال کنید :
                        </h6>
                        <ul class="info-share"> 
                            <li><a target="_blank" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a target="_blank" href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a target="_blank" href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a target="_blank" href="#"><i class="fa fa-github"></i></a></li>
                        </ul>

                    </div>
                    <div class="col-lg-3 col-md-6 mt-4 mt-lg-0">
                        <div class="widget text-left">
                            <div class="textwidget">
                                <h6 class="footer-link-title">اپلیکیشن ما</h6>
                                <div class="d-flex align-items-center">
                                    <a class="app-image" href="#">
                                        <img src="{%static 'images/footer/01.jpg'%}" alt="play-store">
                                    </a><br>
                                    <a class="ml-3 app-image" href="#"><img src="{%static 'images/footer/02.jpg'%}" alt="app-store"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Address END -->
</footer>
    <!-- MainContent End-->
    <!-- back-to-top -->
    <div id="back-to-top">
        <a class="top" href="#top" id="top"> <i class="fa fa-angle-up"></i> </a>
    </div>
    <!-- back-to-top End -->
    <!-- jQuery, Popper JS -->
    <script src="{%static 'js/jquery-3.4.1.min.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
    <!-- Bootstrap JS -->
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <!-- Slick JS -->
    <script src="{%static 'js/slick.min.js'%}"></script>
    <!-- owl carousel Js -->
    <script src="{%static 'js/owl.carousel.min.js'%}"></script>
    <!-- select2 Js -->
    <script src="{%static 'js/select2.min.js'%}"></script>
    <!-- Magnific Popup-->
    <script src="{%static 'js/jquery.magnific-popup.min.js'%}"></script>
    <!-- Slick Animation-->
    <script src="{%static 'js/slick-animation.min.js'%}"></script>
    <!-- Custom JS-->
    <script src="{%static 'js/custom.js'%}"></script>