core/about_us/urls.py
from django.urls import path
from . import views

app_name='about'

urlpatterns=[
    path('about',views.AboutUs.as_view(),name='about_us'),
    path('contact',views.ContactUs.as_view(),name='contact_us'),
    path('questions',views.QuestionView.as_view(),name='questions')
]

core/core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('account/',include('user_profile.urls')),
    path('about/',include('about_us.urls')),
    path('',include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/movie/urls.py
from django.urls import path,include
from movie import views

app_name='movie'

urlpatterns=[
    path('',views.MovieView.as_view(),name='main'),
    path('movies',views.MoviePageView.as_view(),name='movies'),
    path('series',views.SeriePageView.as_view(),name='series'),
    path('movie/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path("series/<slug:slug>/", views.SerieDetailView.as_view(), name="series_detail"),
    path("series/<slug:series_slug>/episode/<int:episode_number>/", views.EpisodeDetailView.as_view(), name="episode_detail"),
    path("movie/<slug:slug>/download/", views.download_movie, name="download_movie"),
    path("series/<slug:series_slug>/episode/<int:episode_number>/download/", views.download_episode, name="download_episode"),
    path("download-report", views.download_report, name="download_report"),
    
]

core/about_us/models.py
from django.db import models
from django.core.validators import RegexValidator

phone_validator=RegexValidator(
    regex=r'^\+?\d{10,15}$',
     message="شماره تلفن باید فقط شامل عدد باشد و بین 10 تا 15 رقم داشته باشد."
)
# Create your models here.
class ContactMessage(models.Model):
    first_name=models.CharField(max_length=255)
    last_name=models.CharField(max_length=255)
    phone=models.CharField(max_length=255)
    email=models.EmailField()
    message=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.email}"
    
class Question(models.Model):
    question=models.CharField(max_length=1000)
    answer=models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.question}-{self.answer[:10]}"

core/about_us/forms.py
from django import forms
from .models import ContactMessage

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['first_name', 'last_name', 'phone', 'email', 'message']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام خانوادگی'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'شماره تلفن'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'ایمیل'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'متن پیام'}),
        }

core/about_us/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,ListView
from django.urls import reverse_lazy
from django.contrib import messages
from .models import ContactMessage,Question
from .forms import ContactForm

# Create your views here.
class AboutUs(TemplateView):
    template_name='about_us/about-us.html'

class ContactUs(CreateView):
    model = ContactMessage
    form_class = ContactForm
    template_name = 'about_us/contact.html'
    success_url = reverse_lazy('about:contact_us')

    def form_valid(self, form):
        messages.success(self.request, "پیام شما با موفقیت ارسال شد ✅")
        return super().form_valid(form)
    
class QuestionView(ListView):
    template_name='about_us/questions.html'
    queryset=Question.objects.all()
    context_object_name='questions'

core/templates/about_us/questions.html
{%load static%}
<!doctype html>
<html dir="rtl" lang="en-US">
   <head>
      <!-- Required meta tags -->
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>sarabi stream</title>
      <!-- Favicon -->
      <link rel="shortcut icon" href="{%static 'images/favicon.ico'%}" />
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}" />
      <!-- Typography CSS -->
      <link rel="stylesheet" href="{%static 'css/typography.css'%}">
      <!-- Style -->
      <link rel="stylesheet" href="{%static 'css/style.css'%}" />
      <!-- Responsive -->
      <link rel="stylesheet" href="{%static 'css/responsive.css'%}" />
   </head>
   <body>
      <!-- loader Start -->
      <div id="loading">
         <div id="loading-center">
         </div>
      </div>
      <!-- loader END -->
      <!-- Header -->
      {%include 'includes/header.html'%}
      <!-- Header End -->
        <div class="iq-breadcrumb-one  iq-bg-over iq-over-dark-50" style="background-image: url('{%static "images/about-us/01.jpg"%}');">  
            <div class="container-fluid"> 
                <div class="row align-items-center">
                    <div class="col-sm-12">
                        <nav aria-label="breadcrumb" class="text-center iq-breadcrumb-two">
                            <h2 class="title">سوالات متداول</h2>
                            <ol class="breadcrumb main-bg">
                                <li class="breadcrumb-item"><a href="{%url 'movie:main'%}">خانه</a></li> 
                                <li class="breadcrumb-item active">سوالات متداول</li>
                            </ol>
                        </nav>
                    </div>
                </div> 
            </div>
        </div>

        <!-- Main container -->  
        
      <main id="main" class="site-main">
         <div class="container">
            <div class="row">
               <div class="col-lg-12 col-sm-12">

                  <div class="iq-accordion iq-accordion-square">

                     {%for question in questions%}
                       <div class="iq-accordion-block iq-active 1">
                        <div class="iq-accordion-title">
                           <div class="iq-icon-right">
                              <i aria-hidden="true" class="fa fa-minus active"></i>
                              <i aria-hidden="true" class="fa fa-plus inactive"></i>
                           </div>
                           <h4 class="mb-0 accordion-title iq-heading-title">         
                            {{question.question}}    
                           </h4>
                        </div>                   
                        <div class="iq-accordion-details" style="display: block;">                         
                           <p class="iq-content-text">{{question.answer}}</p>
                        </div>
                     </div>
                     {%endfor%}                     
                     </div>
               </div>
            </div>
         </div>   
      </main>

        <!-- Main container end -->
        {%include 'includes/footer.html'%}
        </body>
        </html>